name: 'CAF landing zone '
description: 'VolkerWessels purge landing zones'
inputs:
  config_dir:
    description: 'The configuration directory from which to run the commands'
    required: true
  environment:
    description: 'The environment variable used in Azure tags'
    required: true
  landingzone:
    description: 'The segment (launchpad, solution or add-on) of a cloud environment to destroy'
    required: true
  level:
    description: 'The level to destroy'
    required: true
    default: true
  tags:
    description: 'The tags of the resources to destroy'
    required: true
    default: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV;
        echo "TFVARS_PATH=${{ inputs.config_dir }}" >> $GITHUB_ENV;
        echo "BASE_PATH=$(dirname ${{ inputs.config_dir }})" >> $GITHUB_ENV;
      shell: bash
    - name: Remove levels with terraform
      run: make destroy SOLUTION=${{ inputs.landingzone }} LEVEL=${{ inputs.level }}
      shell: bash
